package com.example.quickcash.ui.employerJobPage;

import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.navigation.NavDirections;

import com.example.quickcash.Objects.Job;
import com.example.quickcash.R;

//solution generated by ChatGPT https://chat.openai.com/share/34706809-7805-40c6-b287-321c5df9f9df
//this is needed due to the way in which NavController is used, being needed
//to maintain the surrounding elements like the bottom nav bar
public class EmployerJobPageDirections implements NavDirections {
    private final Bundle args;

    public EmployerJobPageDirections(Job j) {
        args = new Bundle();
        args.putSerializable("job", j);
    }

    @NonNull
    @Override
    public Bundle getArguments() {
        return args;
    }

    @Override
    public int getActionId() {
        return R.id.employerJobPageDestFragment;
    }
}